import type {
  SidebarsConfig,
  SidebarOptions,
} from '@docusaurus/plugin-content-docs';
import {
  Sidebar,
  SidebarConfig,
} from '@docusaurus/plugin-content-docs/src/sidebars/types';
import pluginConfig from './flavor.config';

const { packages, plugins } = pluginConfig;

const packageSidebars = packages.reduce((acc, curr) => {
  const { name, developerDocs } = curr;
  const packageSidebar: SidebarConfig = [
    {
      type: 'autogenerated',
      dirName: name.replace('/', '-'),
    },
  ];

  acc[name] = packageSidebar;
  return acc;
}, {} as Record<string, SidebarConfig>);

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  pluginsSidebar: [{ type: 'autogenerated', dirName: 'plugins' }],
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  ...packageSidebars,
};
console.log('sidebars', sidebars);

export default sidebars;
